/** Same hard-coded list as employee / cashier petty cash expenses. */
export const LOCKER_EXPENSE_CATEGORIES = [
    'Advertising and promotion',
    'Bank charges',
    'Charity / Donations / Reward Expenses',
    'Customer Compensation Expenses',
    'Customer services expenses',
    'Development & Renovation Expenses',
    'Food & Entertainment',
    'Fuel Allowance Expenses',
    'Information Technology Expenses',
    'Labour uniform & shoes Expenses',
    'Medical Expenses',
    'Misc Accommodation Expenses',
    'Misc Expenses',
    'Misc Government Expenses',
    'Motor vehicle Repair Expenses',
    'Municipal / Garbage Expenses - شركة الهلب للتجارية و المقاولات',
    'POL Expenses',
    'Printing and stationery',
    'Repair & maintenance Expenses - Accomodation',
    'Repair & maintenance Expenses - Car Wash',
    'Salary Advances',
];
