import * as XLSX from 'xlsx';
import {
    BILINGUAL_PDF_CSS,
    bilingualHeaderCell,
    bilingualHtml,
    chunkRows,
    escapePdfHtml,
    exportHtmlPagesToPdf,
    splitLatinAndArabic,
} from './bilingualHtmlPdf.js';

const fmtMoney = (v) =>
    Number(v ?? 0).toLocaleString('en-SA', {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
    });

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function fmtPrettyDate(value) {
    const raw = String(value || '').trim();
    const ymd = raw.match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!ymd) return raw;
    return `${Number(ymd[3])} ${MONTHS[Number(ymd[2]) - 1]} ${ymd[1]}`;
}

const CASH_STMT_CSS = `
.cash-stmt{ padding:18px 22px 16px; }
.cash-stmt .hdr-top{ align-items:flex-start; justify-content:space-between; }
.cash-stmt .hdr-brand{ flex:0 0 auto; }
.cash-stmt .hdr-brand-ar{
  width:max-content;
  max-width:280px;
  text-align:right;
  margin-top:2px;
}
.cash-stmt .hdr-logo{ width:42px; height:42px; object-fit:contain; display:block; flex-shrink:0; }
.cash-stmt .hdr-seller{ flex:0 0 auto; text-align:right; }
.cash-stmt .hdr-seller-en{ font-size:13px; font-weight:700; color:#111827; }
.cash-stmt .hdr-seller-ar{
  font-family:"Noto Sans Arabic","Segoe UI",Tahoma,sans-serif;
  font-size:12px; font-weight:600; direction:rtl; unicode-bidi:isolate; color:#334155; margin-top:2px;
}
.cash-stmt .hdr-seller-meta{ font-size:9px; color:#64748b; margin-top:4px; line-height:1.4; }
.cash-stmt .title-row{ margin:12px 0 6px; padding-bottom:8px; border-bottom:1px solid #e2e8f0; }
.cash-stmt .title-en{ font-size:16px; unicode-bidi:isolate; }
.cash-stmt .title-ar{ font-size:15px; unicode-bidi:isolate; }
.cash-stmt .meta-grid{
  display:grid;
  grid-template-columns:1fr 1fr;
  gap:8px 28px;
  font-size:10px;
  color:#475569;
  margin:0 0 12px;
}
.cash-stmt .meta-item{ display:flex; flex-direction:column; gap:2px; }
.cash-stmt .meta-keys{ display:flex; align-items:baseline; gap:8px; }
.cash-stmt .meta-en{ color:#94a3b8; font-weight:600; unicode-bidi:isolate; }
.cash-stmt .meta-ar{
  color:#94a3b8;
  font-family:"Noto Sans Arabic","Segoe UI",Tahoma,sans-serif;
  font-weight:600;
  direction:rtl;
  unicode-bidi:isolate;
}
.cash-stmt .meta-val{ color:#1e293b; font-weight:600; unicode-bidi:isolate; }
.cash-stmt .kpis{ table-layout:fixed; margin-bottom:12px; }
.cash-stmt .kpis .lbl-en{ display:block; font-size:8px; font-weight:700; letter-spacing:.02em; text-transform:uppercase; }
.cash-stmt .kpis .lbl-ar{
  display:block;
  font-family:"Noto Sans Arabic","Segoe UI",Tahoma,sans-serif;
  font-size:9px; font-weight:600; direction:rtl; unicode-bidi:isolate; color:#78350f; margin-top:2px;
}
.cash-stmt .kpis td{ font-size:13px; padding:8px 6px; }
.cash-stmt table.grid{ font-size:9px; }
.cash-stmt table.grid th{ padding:7px 5px; }
.cash-stmt table.grid td{ padding:6px 5px; }
.cash-stmt col.col-date{ width:10%; }
.cash-stmt col.col-acct{ width:16%; }
.cash-stmt col.col-party{ width:18%; }
.cash-stmt col.col-desc{ width:22%; }
.cash-stmt col.col-ref{ width:10%; }
.cash-stmt col.col-num{ width:8%; }
.cash-stmt .open-label .td-en,.cash-stmt .open-label .td-ar{ display:inline; margin:0 6px 0 0; }
`;

function registerTitles(header) {
    const slug = String(header?.registerSlug || header?.registerType || '').toUpperCase();
    if (slug === 'BANK') {
        return { en: 'Bank Register Statement', ar: 'كشف الحساب البنكي' };
    }
    if (slug === 'PETTY_CASH') {
        return { en: 'Petty Cash Register Statement', ar: 'كشف الصندوق النثري' };
    }
    const fallback = String(header?.registerTitle || '').trim();
    if (/bank/i.test(fallback)) return { en: 'Bank Register Statement', ar: 'كشف الحساب البنكي' };
    if (/petty/i.test(fallback)) {
        return { en: 'Petty Cash Register Statement', ar: 'كشف الصندوق النثري' };
    }
    return { en: 'Cash Register Statement', ar: 'كشف الصندوق النقدي' };
}

function moneyHtml(currency, amount) {
    return `${escapePdfHtml(currency)} ${escapePdfHtml(fmtMoney(amount))}`;
}

function kpiHead(en, ar) {
    return `<span class="lbl-en">${escapePdfHtml(en)}</span><span class="lbl-ar">${escapePdfHtml(ar)}</span>`;
}

function metaItem(en, ar, valueHtml) {
    return `<div class="meta-item"><div class="meta-keys"><span class="meta-en">${escapePdfHtml(en)}</span><span class="meta-ar">${escapePdfHtml(ar)}</span></div><div class="meta-val">${valueHtml}</div></div>`;
}

export function buildCashBankRegisterPdfPages({ header, summary, lines, logoSrc = '' }) {
    const titles = registerTitles(header);
    const accountLabel = header?.accountLabel || 'All accounts in this register';
    const accountParts = splitLatinAndArabic(accountLabel);
    const currency = header?.currencyCode || 'SAR';
    const sum = summary ?? {};
    const exportRows = buildExportRows(lines);
    const chunks = chunkRows(exportRows, 11);
    const generated = `This statement was generated by FILTER ERP · ${new Date().toLocaleString()}`;
    const period = `${fmtPrettyDate(header?.from) || '—'}  —  ${fmtPrettyDate(header?.to) || '—'}`;
    const logo = logoSrc
        ? `<img class="hdr-logo" src="${escapePdfHtml(logoSrc)}" alt="FILTER" />`
        : '';

    return chunks.map((chunk, pageIdx) => {
        const isFirst = pageIdx === 0;
        const isLast = pageIdx === chunks.length - 1;
        const kpi = isFirst
            ? `<table class="kpis"><thead><tr>
                <th>${kpiHead('Opening balance', 'الرصيد الافتتاحي')}</th>
                <th>${kpiHead('Total receipts (IN)', 'إجمالي المقبوضات')}</th>
                <th>${kpiHead('Total payments (OUT)', 'إجمالي المدفوعات')}</th>
                <th>${kpiHead('Closing balance', 'الرصيد الختامي')}</th>
               </tr></thead><tbody><tr>
                <td>${moneyHtml(currency, sum.openingBalance)}</td>
                <td>${moneyHtml(currency, sum.totalReceipts)}</td>
                <td>${moneyHtml(currency, sum.totalPayments)}</td>
                <td>${moneyHtml(currency, sum.closingBalance)}</td>
               </tr></tbody></table>`
            : '';
        const opening = isFirst
            ? `<tr class="open"><td colspan="7" class="open-label">${bilingualHtml('Opening balance الرصيد الافتتاحي')}</td><td class="num">${escapePdfHtml(fmtMoney(sum.openingBalance))}</td></tr>`
            : '';
        const closing = isLast
            ? `<tr class="close"><td colspan="7" class="open-label">${bilingualHtml('Closing balance الرصيد الختامي')}</td><td class="num">${escapePdfHtml(fmtMoney(sum.closingBalance))}</td></tr>`
            : '';
        const body = chunk
            .map(
                (r) => `<tr>
                    <td>${bilingualHtml(r.date)}</td>
                    <td>${bilingualHtml(r.coaRegister)}</td>
                    <td>${bilingualHtml(r.paidTo)}</td>
                    <td>${bilingualHtml(r.particulars)}</td>
                    <td>${bilingualHtml(r.reference)}</td>
                    <td class="num in">${r.inAmt > 0 ? escapePdfHtml(fmtMoney(r.inAmt)) : ''}</td>
                    <td class="num out">${r.outAmt > 0 ? escapePdfHtml(fmtMoney(r.outAmt)) : ''}</td>
                    <td class="num">${escapePdfHtml(fmtMoney(r.balance))}</td>
                </tr>`,
            )
            .join('');
        const filterLine = header?.filterNote
            ? metaItem('View', 'العرض', escapePdfHtml(header.filterNote))
            : '';
        const inner = `
            <div class="hdr-top">
              ${logo}
              <div class="hdr-brand">
                <div class="hdr-brand-en">FILTER ERP</div>
                <div class="hdr-brand-ar">فلتر لخدمات السيارات</div>
              </div>
              <div class="hdr-seller">
                <div class="hdr-seller-en">Filter Car Services</div>
                <div class="hdr-seller-ar">فلتر لخدمات السيارات</div>
                <div class="hdr-seller-meta">VAT 311120967500003</div>
              </div>
            </div>
            <div class="title-row">
              <span class="title-en">${escapePdfHtml(titles.en)}</span>
              <span class="title-sep">|</span>
              <span class="title-ar">${escapePdfHtml(titles.ar)}</span>
            </div>
            <div class="meta-grid">
              ${metaItem('Account', 'الحساب', `${escapePdfHtml(accountParts.english || accountLabel)}${accountParts.arabic ? `<span class="td-ar">${escapePdfHtml(accountParts.arabic)}</span>` : ''}`)}
              ${metaItem('Period', 'الفترة', escapePdfHtml(period))}
              ${metaItem('Currency', 'العملة', escapePdfHtml(currency))}
              ${metaItem('Generated', 'تاريخ الإصدار', `${escapePdfHtml(new Date().toLocaleString())}${chunks.length > 1 ? ` · Page ${pageIdx + 1} of ${chunks.length}` : ''}`)}
              ${filterLine}
            </div>
            ${kpi}
            <table class="grid">
                <colgroup>
                  <col class="col-date"/><col class="col-acct"/><col class="col-party"/><col class="col-desc"/>
                  <col class="col-ref"/><col class="col-num"/><col class="col-num"/><col class="col-num"/>
                </colgroup>
                <thead><tr>
                    <th>${bilingualHeaderCell('Date', 'التاريخ')}</th>
                    <th>${bilingualHeaderCell('Account', 'الحساب')}</th>
                    <th>${bilingualHeaderCell('Received from / Paid to', 'المستلم / المدفوع له')}</th>
                    <th>${bilingualHeaderCell('Particulars', 'البيان')}</th>
                    <th>${bilingualHeaderCell('Reference', 'المرجع')}</th>
                    <th class="num">${bilingualHeaderCell('Receipts', 'وارد')}</th>
                    <th class="num">${bilingualHeaderCell('Payments', 'صادر')}</th>
                    <th class="num">${bilingualHeaderCell('Balance', 'الرصيد')}</th>
                </tr></thead>
                <tbody>${opening}${body}${closing}</tbody>
            </table>
            <div class="foot">${escapePdfHtml(generated)}</div>
        `;
        return `<div class="stmt-pdf cash-stmt"><style>@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@400;600;700&display=swap');${BILINGUAL_PDF_CSS}${CASH_STMT_CSS}</style>${inner}</div>`;
    });
}

function safeSlug(s) {
    return String(s || '')
        .replace(/[^\w-]+/g, '_')
        .replace(/_+/g, '_')
        .replace(/^_|_$/g, '');
}

function buildFileBase({ header }) {
    const register = safeSlug(header?.registerSlug || header?.registerTitle || 'register');
    const account = safeSlug(header?.accountSlug || 'all_accounts');
    const range =
        header?.from && header?.to
            ? `${header.from}_to_${header.to}`
            : header?.from
              ? `from_${header.from}`
              : header?.to
                ? `to_${header.to}`
                : 'all';
    return `Cash_Bank_Register_${register}_${account}_${range}`;
}

function mapLineForExport(row) {
    const posted = row.entryDate ? fmtPrettyDate(String(row.entryDate).slice(0, 10)) : '';
    const requested = row.requestedAt ? fmtPrettyDate(String(row.requestedAt).slice(0, 10)) : '';
    const approved = row.approvedAt ? fmtPrettyDate(String(row.approvedAt).slice(0, 10)) : posted;
    const date = requested ? `Requested ${requested}\nApproved ${approved}` : posted;
    const coaPart = row.coaCode ? `[${row.coaCode}] ${row.coaName || ''}` : row.accountName || '';
    const coaRegister =
        row.accountName && row.coaCode ? `${coaPart} — ${row.accountName}` : coaPart || row.accountName || '';
    const inAmt = row.direction === 'in' ? Number(row.amount ?? 0) : 0;
    const outAmt = row.direction === 'out' ? Number(row.amount ?? 0) : 0;
    const purpose = String(row.offsetAccountLabel || '').trim();
    const description = String(row.description || '').trim();
    const particulars = [purpose, description].filter(Boolean).join('\n');
    return {
        date,
        coaRegister,
        paidTo: row.counterpartyLabel || '',
        purpose,
        description,
        particulars,
        reference: row.reference || row.sourceType || '',
        inAmt,
        outAmt,
        balance: Number(row.balance ?? 0),
    };
}

function buildExportRows(lines) {
    return (lines ?? []).map(mapLineForExport);
}

/**
 * Professional Cash / Bank / Petty Cash register statement — PDF download.
 * Renders HTML (split EN/AR + Noto/Segoe) then captures to PDF.
 */
export async function exportCashBankRegisterPdf({ header, summary, lines }) {
    let logoSrc = '';
    try {
        const mod = await import('../assets/images/filter-brand-icon.png');
        logoSrc = mod.default || '';
    } catch {
        logoSrc = '';
    }
    const pages = buildCashBankRegisterPdfPages({ header, summary, lines, logoSrc });
    await exportHtmlPagesToPdf({
        fileName: `${buildFileBase({ header })}.pdf`,
        orientation: 'landscape',
        pages,
    });
}

/**
 * Professional Cash / Bank / Petty Cash register statement — Excel download.
 */
export function exportCashBankRegisterExcel({ header, summary, lines }) {
    const company = header?.companyName || 'FILTER ERP';
    const registerTitle = header?.registerTitle || 'Cash Register Statement';
    const accountLabel = header?.accountLabel || 'All accounts in this register';
    const currency = header?.currencyCode || 'SAR';
    const sum = summary ?? {};
    const exportRows = buildExportRows(lines);

    const aoa = [
        [company],
        [registerTitle],
        ['Cash & Bank Register Statement'],
        [],
        ['Register', registerTitle],
        ['Account', accountLabel],
        ['Period', `${header?.from || '—'}  to  ${header?.to || '—'}`],
        ['Currency', currency],
        ...(header?.filterNote ? [['View', header.filterNote]] : []),
        [],
        ['Summary'],
        ['Opening Balance', Number(sum.openingBalance ?? 0)],
        ['Total Receipts (IN)', Number(sum.totalReceipts ?? 0)],
        ['Total Payments (OUT)', Number(sum.totalPayments ?? 0)],
        ['Closing Balance', Number(sum.closingBalance ?? 0)],
        [],
        [
            'Date',
            'COA / Register',
            'Paid to / Received from',
            'For / purpose',
            'Description',
            'Reference',
            `IN (${currency})`,
            `OUT (${currency})`,
            `Balance (${currency})`,
        ],
        ['—', '—', '—', '—', 'Opening balance', '—', '', '', Number(sum.openingBalance ?? 0)],
        ...exportRows.map((r) => [
            r.date,
            r.coaRegister,
            r.paidTo,
            r.purpose,
            r.description,
            r.reference,
            r.inAmt > 0 ? Number(r.inAmt) : '',
            r.outAmt > 0 ? Number(r.outAmt) : '',
            Number(r.balance ?? 0),
        ]),
        ['—', '—', '—', '—', 'Closing balance', '—', '', '', Number(sum.closingBalance ?? 0)],
        [],
        ['Generated', new Date().toLocaleString()],
    ];

    const ws = XLSX.utils.aoa_to_sheet(aoa);
    ws['!cols'] = [
        { wch: 14 },
        { wch: 32 },
        { wch: 26 },
        { wch: 28 },
        { wch: 40 },
        { wch: 16 },
        { wch: 14 },
        { wch: 14 },
        { wch: 16 },
    ];

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Register');
    XLSX.writeFile(wb, `${buildFileBase({ header })}.xlsx`);
}
